appId: com.android.settings
name: Turn on Wi-Fi (Android)
platform: android
---
- launchApp
- wait: 2
- tap: 'Network & internet'
- tap: 'Internet'
- tap: 'Use Wi-Fi'
- done: 'Wi-Fi toggled successfully'
